name: deploy_firebase_hosting
on:
  push:
    paths: 
      - build/**
    branches: [ main ]
jobs:
  deploy_firebase_hosting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@main
      - name: Install
        run: npm install
      - name: Install Firebase-tools
        run: npm install -D firebase-tools
      - name: Deploy to Firebase
        run: npx firebase deploy --token=${{ secrets.FIREBASE_TOKEN }}
