name: deploy_firebase_hosting
on:
  push:
    branches: [ main ]
jobs:
  deploy_firebase_hosting:
    runs-on: macos-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@main
      - name: Install Deploy tool
        run: npm install -D firebase-tools
      - name: Deploy to Firebase
        run: npm deploy --token=${{ secrets.FIREBASE_TOKEN }}
