name: deploy_firebase_hosting
on:
  push:
    branches: [ main ]
jobs:
  deploy_firebase_hosting:
    runs-on: macos-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@main
      - name: Deploy to Firebase
        run: npx firebase deploy --token=${{ secrets.FIREBASE_TOKEN }}
